apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-deploy
  template:
    metadata:
      labels:
        app: app-deploy
    spec:
      containers:
      - name: mydemo
        image: 048981882745.dkr.ecr.us-east-1.amazonaws.com/demo
        ports:
          - containerPort: 80
